source 'https://rubygems.org'

gem 'jekyll', :github => 'ixti/jekyll'
gem 'jekyll-assets'
gem 'rake'
gem 'redcarpet'
gem 'rqrcode'
gem 'rmagick'
gem 'rubyzip'
gem 'sprockets', '~> 2.8.0'
gem 'sass'
gem 'uglifier'
